require './privacy'

module AppConst
  SMTP_GMAIL_ADDRESS = 'smtp.gmail.com'
  SMTP_GMAIL_PORT = 587
  SMTP_GMAIL_DOMAIN = 'gmail.com'
  SMTP_GMAIL_USER_NAME = Privacy::SMTP_GMAIL_USER_NAME
  SMTP_GMAIL_PASSWORD = Privacy::SMTP_GMAIL_PASSWORD
  SMTP_GMAIL_AUTHENTICATION = :login
  SMTP_GMAIL_ENABLE_STARTTLS_AUTO = true
end
